package com.dksd.dvim.event;

public enum EventType {
    KEY_PRESS, BUF_ENTER, BUF_EXIT, KEY_COMPLETE,
    TELESCOPE_CLOSE, SEARCH_CLOSE,
    BUF_CHANGE_ADD,
    BUF_CHANGE_REMOVE,
    BUF_CHANGE_INSERT,
    MODE_CHANGE

}
