package com.dksd.dvim.buffer;

public enum BufferMode {
    SINGLE_LINE_INPUT,
    READ_ONLY,
    READ_ONLY_MODAL,
    NO_LINE_NUMBERS,
    FIXED_HEIGHT,
    FIXED_WIDTH,
    UNSELECTABLE,
    ABS_POS,
    RELATIVE_HEIGHT,
    RELATIVE_LEFT_START,
    POS_BELOW_CURSOR,
    LEFT_BORDER,
    TOP_BORDER,
    RIGHT_BORDER,
    BOT_BORDER,
    POP_OVER, NO_GUTTER, SINGLE_LINE, ALLOW_UNDO, NORMAL
}
